### ISSUE TITLE
EDDiscovery crashing when controller is disconnected

### ISSUE THREAD

**Issue by jjwfisher** [wulkanat/EDDX52#4]
In the latest version of EDDiscovery (11.9.3), after inserting DirectOutput.dll and EDX52.dll inside the correct folder, and giving EDDiscovery permission to access the dlls, EDDiscovery enters an unrecoverable crashed state.

I assume one or both of the dll files is now out of date & cannot work with EDDiscovery?

**Comment by jjwfisher** [comment]
I have also realised that I was testing this without the X52 plugged in. I will close this issue for now as I cannot test it with the joystick yet. Apologies.

**Comment by Theaninova** [comment]
I'm still going to reopen this as an issue, not sure when (and honestly if) I'm going to fix it, been a few years since I worked on it but it probably is an easy fix to prevent the crash.

**Comment by jjwfisher** [comment]
Okay, that's very kind thank you. I will also test with joystick plugged in when I can, if there isn't a new release by then. If you need any system info let me know also :)

**Comment by Theaninova** [comment]
There is a lot of mistakes made here, maybe I'll do a rewrite some time, especially as I haven't touched in years, and the code is probably very buggy anyways... This was back when I wasn't really all that good. I think I'm gonna take this as an opportunity to test some stuff I've always wanted to try (can't make any promises though).

**Comment by jjwfisher** [comment]
Okay! I've watched this repo anyway, and I'll be happy to bug test anything you can produce (no pressure though of course!)

I'd offer to help, but unfortunately I have zero experience with C++ or .dll files.
